### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by 0nkery**
I suggest to start working on the documentation.

I created demo at ReadTheDocs - http://muffin-docs.readthedocs.org/en/latest. 

It's mostly copy-paste from README by now (with some fixes).

PS. I know about your docs there - update them and place link to README, please.

### CODE REVIEW

**Comment by klen** [comment]
The PR is great. Thank you!

**Comment by klen** [comment]
What link in README you want me to update?

**Comment by 0nkery** [comment]
Add this link somewhere in README, please.

http://muffin.readthedocs.org/en/latest/

And rebuild your ReadTheDocs project.

If you wish we could stay at my demo-project, but it's not so convenient.

**Comment by klen** [comment]
Done.

**Comment by 0nkery** [comment]
Thanks!

**Pull request merged**
